-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_src_SubcarrierSelector.vhd
-- Created: 2025-11-19 10:43:19
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_src_SubcarrierSelector
-- Source Path: 
-- Hierarchy Level: 3
-- Model version: 8.98
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Demodulat_ip_src_SubcarrierSelector IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        varargout_1_re                    :   IN    std_logic_vector(43 DOWNTO 0);  -- sfix44_En30
        varargout_1_im                    :   IN    std_logic_vector(43 DOWNTO 0);  -- sfix44_En30
        varargout_2                       :   IN    std_logic;
        varargout_1_re_1                  :   OUT   std_logic_vector(43 DOWNTO 0);  -- sfix44_En30
        varargout_1_im_1                  :   OUT   std_logic_vector(43 DOWNTO 0);  -- sfix44_En30
        varargout_2_1                     :   OUT   std_logic
        );
END Demodulat_ip_src_SubcarrierSelector;


ARCHITECTURE rtl OF Demodulat_ip_src_SubcarrierSelector IS

  -- Signals
  SIGNAL obj_SubcarrierSelectorObj_resetSig : std_logic;
  SIGNAL obj_SubcarrierSelectorObj_validIn : std_logic;
  SIGNAL tmp                              : std_logic;
  SIGNAL obj_SubcarrierSelectorObj_validIn_1 : std_logic;
  SIGNAL obj_SubcarrierSelectorObj_dataOut_re : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataOut_im : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_FFTLength : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_FFTLength_1 : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_1                            : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_FFTLength_2 : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_vecStepCount : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_vecStepCount_1 : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_2                            : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_3                            : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_vecStepCount_2 : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_4                            : std_logic;
  SIGNAL tmp_5                            : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_6                            : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_7                            : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_numLGSC : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_numLGSC_1 : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_8                            : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_numLGSC_2 : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_9                            : std_logic;
  SIGNAL tmp_10                           : std_logic;
  SIGNAL obj_SubcarrierSelectorObj_numRGSC : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_11                           : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_FFTMinusRG : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL obj_SubcarrierSelectorObj_FFTMinusRG_1 : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_12                           : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_13                           : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_14                           : unsigned(16 DOWNTO 0);  -- ufix17
  SIGNAL tmp_15                           : std_logic;
  SIGNAL guard1                           : std_logic;
  SIGNAL guard1_1                         : std_logic;
  SIGNAL guard1_2                         : std_logic;
  SIGNAL tmp_16                           : std_logic;
  SIGNAL tmp_17                           : std_logic;
  SIGNAL tmp_18                           : std_logic;
  SIGNAL tmp_19                           : std_logic;
  SIGNAL varargout_1_re_signed            : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL varargout_1_im_signed            : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataIn_re : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataIn_im : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_re                           : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_im                           : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataIn_re_1 : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataIn_im_1 : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataOut_re_1 : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataOut_im_1 : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataOut_re_2 : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataOut_im_2 : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataOut_re_3 : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_dataOut_im_3 : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_re_1                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_im_1                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_re_2                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_im_2                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_re_3                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_im_3                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_re_4                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_im_4                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_re_5                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL tmp_im_5                         : signed(43 DOWNTO 0);  -- sfix44_En30
  SIGNAL obj_SubcarrierSelectorObj_validOut : std_logic;
  SIGNAL tmp_20                           : std_logic;
  SIGNAL tmp_21                           : std_logic;
  SIGNAL obj_SubcarrierSelectorObj_validOut_1 : std_logic;
  SIGNAL obj_SubcarrierSelectorObj_validOut_2 : std_logic;
  SIGNAL obj_SubcarrierSelectorObj_validOut_3 : std_logic;
  SIGNAL obj_SubcarrierSelectorObj_validOut_4 : std_logic;
  SIGNAL tmp_22                           : std_logic;
  SIGNAL tmp_23                           : std_logic;
  SIGNAL tmp_24                           : std_logic;
  SIGNAL tmp_25                           : std_logic;
  SIGNAL tmp_26                           : std_logic;

BEGIN
  obj_SubcarrierSelectorObj_resetSig <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp74
  obj_SubcarrierSelectorObj_validIn <= '0';

  
  tmp <= varargout_2 WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_validIn;

  obj_SubcarrierSelectorObj_validIn_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_SubcarrierSelectorObj_validIn_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_SubcarrierSelectorObj_validIn_1 <= tmp;
      END IF;
    END IF;
  END PROCESS obj_SubcarrierSelectorObj_validIn_reg_process;


  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp111
  obj_SubcarrierSelectorObj_dataOut_re <= to_signed(0, 44);
  obj_SubcarrierSelectorObj_dataOut_im <= to_signed(0, 44);

  obj_SubcarrierSelectorObj_FFTLength <= to_unsigned(16#01000#, 17);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp65
  obj_SubcarrierSelectorObj_FFTLength_1 <= to_unsigned(16#00040#, 17);

  
  tmp_1 <= obj_SubcarrierSelectorObj_FFTLength WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_FFTLength_1;

  obj_SubcarrierSelectorObj_FFTLength_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_SubcarrierSelectorObj_FFTLength_2 <= to_unsigned(16#00040#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_SubcarrierSelectorObj_FFTLength_2 <= tmp_1;
      END IF;
    END IF;
  END PROCESS obj_SubcarrierSelectorObj_FFTLength_reg_process;


  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp214
  obj_SubcarrierSelectorObj_vecStepCount <= to_unsigned(16#00000#, 17);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp53
  obj_SubcarrierSelectorObj_vecStepCount_1 <= to_unsigned(16#00000#, 17);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp87
  tmp_3 <= tmp_2 + to_unsigned(16#00001#, 17);

  
  tmp_4 <= '1' WHEN obj_SubcarrierSelectorObj_vecStepCount_2 = obj_SubcarrierSelectorObj_FFTLength_2 ELSE
      '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp104
  
  tmp_5 <= obj_SubcarrierSelectorObj_vecStepCount_2 WHEN tmp_4 = '0' ELSE
      obj_SubcarrierSelectorObj_vecStepCount;

  
  tmp_2 <= obj_SubcarrierSelectorObj_vecStepCount_2 WHEN obj_SubcarrierSelectorObj_validIn_1 = '0' ELSE
      tmp_5;

  
  tmp_6 <= tmp_2 WHEN varargout_2 = '0' ELSE
      tmp_3;

  
  tmp_7 <= tmp_6 WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_vecStepCount_1;

  obj_SubcarrierSelectorObj_vecStepCount_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_SubcarrierSelectorObj_vecStepCount_2 <= to_unsigned(16#00000#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_SubcarrierSelectorObj_vecStepCount_2 <= tmp_7;
      END IF;
    END IF;
  END PROCESS obj_SubcarrierSelectorObj_vecStepCount_reg_process;


  obj_SubcarrierSelectorObj_numLGSC <= to_unsigned(16#001FA#, 17);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp62
  obj_SubcarrierSelectorObj_numLGSC_1 <= to_unsigned(16#00006#, 17);

  
  tmp_8 <= obj_SubcarrierSelectorObj_numLGSC WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_numLGSC_1;

  obj_SubcarrierSelectorObj_numLGSC_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_SubcarrierSelectorObj_numLGSC_2 <= to_unsigned(16#00006#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_SubcarrierSelectorObj_numLGSC_2 <= tmp_8;
      END IF;
    END IF;
  END PROCESS obj_SubcarrierSelectorObj_numLGSC_reg_process;


  
  tmp_9 <= '1' WHEN obj_SubcarrierSelectorObj_vecStepCount_2 > obj_SubcarrierSelectorObj_numLGSC_2 ELSE
      '0';

  
  tmp_10 <= '1' WHEN tmp_2 = to_unsigned(16#00000#, 17) ELSE
      '0';

  obj_SubcarrierSelectorObj_numRGSC <= to_unsigned(16#001FA#, 17);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp89
  tmp_11 <= obj_SubcarrierSelectorObj_FFTLength - obj_SubcarrierSelectorObj_numRGSC;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp29
  obj_SubcarrierSelectorObj_FFTMinusRG <= to_unsigned(16#00040#, 17);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp81
  
  tmp_12 <= obj_SubcarrierSelectorObj_FFTMinusRG_1 WHEN tmp_10 = '0' ELSE
      tmp_11;

  
  tmp_13 <= obj_SubcarrierSelectorObj_FFTMinusRG_1 WHEN varargout_2 = '0' ELSE
      tmp_12;

  
  tmp_14 <= tmp_13 WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_FFTMinusRG;

  obj_SubcarrierSelectorObj_FFTMinusRG_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_SubcarrierSelectorObj_FFTMinusRG_1 <= to_unsigned(16#00040#, 17);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_SubcarrierSelectorObj_FFTMinusRG_1 <= tmp_14;
      END IF;
    END IF;
  END PROCESS obj_SubcarrierSelectorObj_FFTMinusRG_reg_process;


  
  tmp_15 <= '1' WHEN obj_SubcarrierSelectorObj_vecStepCount_2 <= obj_SubcarrierSelectorObj_FFTMinusRG_1 ELSE
      '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp210
  guard1 <= '1';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp200
  guard1_1 <= '1';

  guard1_2 <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp200
  
  tmp_16 <= guard1 WHEN tmp_15 = '0' ELSE
      guard1_2;

  
  tmp_17 <= guard1_1 WHEN tmp_9 = '0' ELSE
      tmp_16;

  
  tmp_18 <= '1' WHEN obj_SubcarrierSelectorObj_vecStepCount_2 > obj_SubcarrierSelectorObj_numLGSC_2 ELSE
      '0';

  
  tmp_19 <= '1' WHEN obj_SubcarrierSelectorObj_vecStepCount_2 <= obj_SubcarrierSelectorObj_FFTMinusRG_1 ELSE
      '0';

  varargout_1_re_signed <= signed(varargout_1_re);

  varargout_1_im_signed <= signed(varargout_1_im);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp77
  obj_SubcarrierSelectorObj_dataIn_re <= to_signed(0, 44);
  obj_SubcarrierSelectorObj_dataIn_im <= to_signed(0, 44);

  
  tmp_re <= varargout_1_re_signed WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_dataIn_re;
  
  tmp_im <= varargout_1_im_signed WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_dataIn_im;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp207
  obj_SubcarrierSelectorObj_dataIn_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_SubcarrierSelectorObj_dataIn_re_1 <= to_signed(0, 44);
      obj_SubcarrierSelectorObj_dataIn_im_1 <= to_signed(0, 44);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_SubcarrierSelectorObj_dataIn_re_1 <= tmp_re;
        obj_SubcarrierSelectorObj_dataIn_im_1 <= tmp_im;
      END IF;
    END IF;
  END PROCESS obj_SubcarrierSelectorObj_dataIn_reg_process;


  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp192
  obj_SubcarrierSelectorObj_dataOut_re_1 <= to_signed(0, 44);
  obj_SubcarrierSelectorObj_dataOut_im_1 <= to_signed(0, 44);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp71
  obj_SubcarrierSelectorObj_dataOut_re_2 <= to_signed(0, 44);
  obj_SubcarrierSelectorObj_dataOut_im_2 <= to_signed(0, 44);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp197
  
  tmp_re_1 <= obj_SubcarrierSelectorObj_dataOut_re_3 WHEN tmp_19 = '0' ELSE
      obj_SubcarrierSelectorObj_dataIn_re_1;
  
  tmp_im_1 <= obj_SubcarrierSelectorObj_dataOut_im_3 WHEN tmp_19 = '0' ELSE
      obj_SubcarrierSelectorObj_dataIn_im_1;

  
  tmp_re_2 <= obj_SubcarrierSelectorObj_dataOut_re_3 WHEN tmp_18 = '0' ELSE
      tmp_re_1;
  
  tmp_im_2 <= obj_SubcarrierSelectorObj_dataOut_im_3 WHEN tmp_18 = '0' ELSE
      tmp_im_1;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp111
  
  tmp_re_3 <= tmp_re_2 WHEN tmp_17 = '0' ELSE
      obj_SubcarrierSelectorObj_dataOut_re_1;
  
  tmp_im_3 <= tmp_im_2 WHEN tmp_17 = '0' ELSE
      obj_SubcarrierSelectorObj_dataOut_im_1;

  
  tmp_re_4 <= obj_SubcarrierSelectorObj_dataOut_re WHEN obj_SubcarrierSelectorObj_validIn_1 = '0' ELSE
      tmp_re_3;
  
  tmp_im_4 <= obj_SubcarrierSelectorObj_dataOut_im WHEN obj_SubcarrierSelectorObj_validIn_1 = '0' ELSE
      tmp_im_3;

  
  tmp_re_5 <= tmp_re_4 WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_dataOut_re_2;
  
  tmp_im_5 <= tmp_im_4 WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_dataOut_im_2;

  obj_SubcarrierSelectorObj_dataOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_SubcarrierSelectorObj_dataOut_re_3 <= to_signed(0, 44);
      obj_SubcarrierSelectorObj_dataOut_im_3 <= to_signed(0, 44);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_SubcarrierSelectorObj_dataOut_re_3 <= tmp_re_5;
        obj_SubcarrierSelectorObj_dataOut_im_3 <= tmp_im_5;
      END IF;
    END IF;
  END PROCESS obj_SubcarrierSelectorObj_dataOut_reg_process;


  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp107
  obj_SubcarrierSelectorObj_validOut <= '0';

  
  tmp_20 <= '1' WHEN obj_SubcarrierSelectorObj_vecStepCount_2 > obj_SubcarrierSelectorObj_numLGSC_2 ELSE
      '0';

  
  tmp_21 <= '1' WHEN obj_SubcarrierSelectorObj_vecStepCount_2 <= obj_SubcarrierSelectorObj_FFTMinusRG_1 ELSE
      '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp204
  obj_SubcarrierSelectorObj_validOut_1 <= '1';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp190
  obj_SubcarrierSelectorObj_validOut_2 <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp68
  obj_SubcarrierSelectorObj_validOut_3 <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp194
  
  tmp_22 <= obj_SubcarrierSelectorObj_validOut_4 WHEN tmp_21 = '0' ELSE
      obj_SubcarrierSelectorObj_validOut_1;

  
  tmp_23 <= obj_SubcarrierSelectorObj_validOut_4 WHEN tmp_20 = '0' ELSE
      tmp_22;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp107
  
  tmp_24 <= tmp_23 WHEN tmp_17 = '0' ELSE
      obj_SubcarrierSelectorObj_validOut_2;

  
  tmp_25 <= obj_SubcarrierSelectorObj_validOut WHEN obj_SubcarrierSelectorObj_validIn_1 = '0' ELSE
      tmp_24;

  
  tmp_26 <= tmp_25 WHEN obj_SubcarrierSelectorObj_resetSig = '0' ELSE
      obj_SubcarrierSelectorObj_validOut_3;

  obj_SubcarrierSelectorObj_validOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_SubcarrierSelectorObj_validOut_4 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_SubcarrierSelectorObj_validOut_4 <= tmp_26;
      END IF;
    END IF;
  END PROCESS obj_SubcarrierSelectorObj_validOut_reg_process;


  varargout_1_re_1 <= std_logic_vector(obj_SubcarrierSelectorObj_dataOut_re_3);

  varargout_1_im_1 <= std_logic_vector(obj_SubcarrierSelectorObj_dataOut_im_3);

  varargout_2_1 <= obj_SubcarrierSelectorObj_validOut_4;

END rtl;

