-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_axis_a_slave.vhd
-- Created: 2025-11-19 10:43:26
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_axis_a_slave
-- Source Path: Demodulat_ip/Demodulat_ip_axis_a_slave
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Demodulat_ip_pkg.ALL;

ENTITY Demodulat_ip_axis_a_slave IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AXIS_A_Slave_TDATA                :   IN    vector_of_std_logic_vector32(0 TO 1);  -- ufix32 [2]
        AXIS_A_Slave_TVALID               :   IN    std_logic;  -- ufix1
        auto_ready                        :   IN    std_logic;  -- ufix1
        AXIS_A_Slave_TREADY               :   OUT   std_logic;  -- ufix1
        user_data                         :   OUT   vector_of_std_logic_vector32(0 TO 1);  -- ufix32 [2]
        user_valid                        :   OUT   std_logic  -- ufix1
        );
END Demodulat_ip_axis_a_slave;


ARCHITECTURE rtl OF Demodulat_ip_axis_a_slave IS

  -- Component Declarations
  COMPONENT Demodulat_ip_fifo_data
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          Empty                           :   OUT   std_logic;  -- ufix1
          Full                            :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT Demodulat_ip_fifo_data_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Demodulat_ip_fifo_data
    USE ENTITY work.Demodulat_ip_fifo_data(rtl);

  FOR ALL : Demodulat_ip_fifo_data_block
    USE ENTITY work.Demodulat_ip_fifo_data_block(rtl);

  -- Signals
  SIGNAL fifo_rd_ack                      : std_logic;  -- ufix1
  SIGNAL fifo_empty                       : std_logic;  -- ufix1
  SIGNAL fifo_full                        : std_logic;  -- ufix1
  SIGNAL stream_in_fifo_user_data         : vector_of_std_logic_vector32(0 TO 1);  -- ufix32 [2]
  SIGNAL fifo_empty_neg                   : std_logic;  -- ufix1
  SIGNAL stream_in_user_valid             : std_logic;  -- ufix1

BEGIN
  u_Demodulat_ip_fifo_data_inst : Demodulat_ip_fifo_data
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => AXIS_A_Slave_TDATA(0),  -- ufix32
              Push => AXIS_A_Slave_TVALID,  -- ufix1
              Pop => fifo_rd_ack,  -- ufix1
              Out_rsvd => stream_in_fifo_user_data(0),  -- ufix32
              Empty => fifo_empty,  -- ufix1
              Full => fifo_full  -- ufix1
              );

  u_Demodulat_ip_fifo_data_inst_1 : Demodulat_ip_fifo_data_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => AXIS_A_Slave_TDATA(1),  -- ufix32
              Push => AXIS_A_Slave_TVALID,  -- ufix1
              Pop => fifo_rd_ack,  -- ufix1
              Out_rsvd => stream_in_fifo_user_data(1)  -- ufix32
              );

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      fifo_rd_ack <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        fifo_rd_ack <= auto_ready;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  AXIS_A_Slave_TREADY <=  NOT fifo_full;


  fifo_empty_neg <=  NOT fifo_empty;

  stream_in_user_valid <= fifo_empty_neg AND fifo_rd_ack;

  user_data <= stream_in_fifo_user_data;

  user_valid <= stream_in_user_valid;

END rtl;

