-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_src_HDL_Algorithm.vhd
-- Created: 2025-12-04 17:31:13
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_src_HDL_Algorithm
-- Source Path: genhdlOFDMDemodulatorChEstModel/Demodulation and Channel Estimation/HDL Algorithm
-- Hierarchy Level: 1
-- Model version: 8.101
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Demodulat_ip_src_HDL_Algorithm IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn_re                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataIn_im                         :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validIn                           :   IN    std_logic;
        refData_re                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        refData_im                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        refValid                          :   IN    std_logic;
        numScPerSym                       :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        reset_1                           :   IN    std_logic;
        dataOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataOut_im                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validOut                          :   OUT   std_logic
        );
END Demodulat_ip_src_HDL_Algorithm;


ARCHITECTURE rtl OF Demodulat_ip_src_HDL_Algorithm IS

  -- Component Declarations
  COMPONENT Demodulat_ip_src_OFDM_Channel_Estimator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1_re                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          In1_im                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          In2                             :   IN    std_logic;
          In3_re                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          In3_im                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          In4                             :   IN    std_logic;
          numSCPS                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          reset_1                         :   IN    std_logic;
          Out1_re                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Out1_im                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          Out2                            :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Demodulat_ip_src_OFDM_Channel_Estimator
    USE ENTITY work.Demodulat_ip_src_OFDM_Channel_Estimator(rtl);

  -- Signals
  SIGNAL OFDM_Channel_Estimator_out1_re   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL OFDM_Channel_Estimator_out1_im   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL OFDM_Channel_Estimator_out2      : std_logic;

BEGIN
  u_OFDM_Channel_Estimator : Demodulat_ip_src_OFDM_Channel_Estimator
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In1_re => dataIn_re,  -- sfix16_En14
              In1_im => dataIn_im,  -- sfix16_En14
              In2 => validIn,
              In3_re => refData_re,  -- sfix16_En14
              In3_im => refData_im,  -- sfix16_En14
              In4 => refValid,
              numSCPS => numScPerSym,  -- uint16
              reset_1 => reset_1,
              Out1_re => OFDM_Channel_Estimator_out1_re,  -- sfix16_En14
              Out1_im => OFDM_Channel_Estimator_out1_im,  -- sfix16_En14
              Out2 => OFDM_Channel_Estimator_out2
              );

  dataOut_re <= OFDM_Channel_Estimator_out1_re;

  dataOut_im <= OFDM_Channel_Estimator_out1_im;

  validOut <= OFDM_Channel_Estimator_out2;

END rtl;

