-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_src_HDLFFTShift.vhd
-- Created: 2025-12-04 17:31:13
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_src_HDLFFTShift
-- Source Path: 
-- Hierarchy Level: 3
-- Model version: 8.101
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Demodulat_ip_src_HDLFFTShift IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        varargout_1_re                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        varargout_1_im                    :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        varargout_2                       :   IN    std_logic;
        varargout_1_re_1                  :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        varargout_1_im_1                  :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        varargout_2_1                     :   OUT   std_logic
        );
END Demodulat_ip_src_HDLFFTShift;


ARCHITECTURE rtl OF Demodulat_ip_src_HDLFFTShift IS

  -- Signals
  SIGNAL obj_FFTShiftTDObj_resetSig       : std_logic;
  SIGNAL varargout_1_re_signed            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL varargout_1_im_signed            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp                              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_FFTShiftTDObj_count          : std_logic;
  SIGNAL obj_FFTShiftTDObj_count_1        : std_logic;
  SIGNAL obj_FFTShiftTDObj_count_2        : std_logic;
  SIGNAL obj_FFTShiftTDObj_count_3        : std_logic;
  SIGNAL tmp_1                            : std_logic;
  SIGNAL tmp_2                            : std_logic;
  SIGNAL tmp_3                            : std_logic;
  SIGNAL tmp_4                            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL yfi                              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL p28yfi_cast                      : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL p28yfi_cast_1                    : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_5                            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_6                            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_FFTShiftTDObj_rePart         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_7                            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_FFTShiftTDObj_rePart_1       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_8                            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_9                            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL yfi_1                            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL p27yfi_cast                      : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL p27yfi_cast_1                    : signed(16 DOWNTO 0);  -- sfix17_En14
  SIGNAL tmp_10                           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_11                           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_FFTShiftTDObj_imPart         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_12                           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_FFTShiftTDObj_imPart_1       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL varargout_1_re_tmp               : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL varargout_1_im_tmp               : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_FFTShiftTDObj_validOut       : std_logic;
  SIGNAL tmp_13                           : std_logic;
  SIGNAL obj_FFTShiftTDObj_validOut_1     : std_logic;

BEGIN
  obj_FFTShiftTDObj_resetSig <= '0';

  varargout_1_re_signed <= signed(varargout_1_re);

  varargout_1_im_signed <= signed(varargout_1_im);

  tmp <= varargout_1_re_signed;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp19
  obj_FFTShiftTDObj_count <= '1';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp19
  obj_FFTShiftTDObj_count_1 <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp7
  obj_FFTShiftTDObj_count_2 <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp15
  
  tmp_1 <= obj_FFTShiftTDObj_count WHEN obj_FFTShiftTDObj_count_3 = '0' ELSE
      obj_FFTShiftTDObj_count_1;

  
  tmp_2 <= obj_FFTShiftTDObj_count_3 WHEN varargout_2 = '0' ELSE
      tmp_1;

  
  tmp_3 <= tmp_2 WHEN obj_FFTShiftTDObj_resetSig = '0' ELSE
      obj_FFTShiftTDObj_count_2;

  obj_FFTShiftTDObj_count_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_FFTShiftTDObj_count_3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_FFTShiftTDObj_count_3 <= tmp_3;
      END IF;
    END IF;
  END PROCESS obj_FFTShiftTDObj_count_reg_process;


  tmp_4 <= varargout_1_re_signed;

  p28yfi_cast <= resize(varargout_1_re_signed, 17);
  p28yfi_cast_1 <=  - (p28yfi_cast);
  
  yfi <= X"7FFF" WHEN (p28yfi_cast_1(16) = '0') AND (p28yfi_cast_1(15) /= '0') ELSE
      X"8000" WHEN (p28yfi_cast_1(16) = '1') AND (p28yfi_cast_1(15) /= '1') ELSE
      p28yfi_cast_1(15 DOWNTO 0);

  
  tmp_5 <= tmp_4 WHEN obj_FFTShiftTDObj_count_3 = '0' ELSE
      yfi;

  
  tmp_6 <= tmp WHEN varargout_2 = '0' ELSE
      tmp_5;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp13
  obj_FFTShiftTDObj_rePart <= to_signed(16#0000#, 16);

  
  tmp_7 <= tmp_6 WHEN obj_FFTShiftTDObj_resetSig = '0' ELSE
      obj_FFTShiftTDObj_rePart;

  obj_FFTShiftTDObj_rePart_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_FFTShiftTDObj_rePart_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_FFTShiftTDObj_rePart_1 <= tmp_7;
      END IF;
    END IF;
  END PROCESS obj_FFTShiftTDObj_rePart_reg_process;


  tmp_8 <= varargout_1_im_signed;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl
  tmp_9 <= varargout_1_im_signed;

  p27yfi_cast <= resize(varargout_1_im_signed, 17);
  p27yfi_cast_1 <=  - (p27yfi_cast);
  
  yfi_1 <= X"7FFF" WHEN (p27yfi_cast_1(16) = '0') AND (p27yfi_cast_1(15) /= '0') ELSE
      X"8000" WHEN (p27yfi_cast_1(16) = '1') AND (p27yfi_cast_1(15) /= '1') ELSE
      p27yfi_cast_1(15 DOWNTO 0);

  
  tmp_10 <= tmp_9 WHEN obj_FFTShiftTDObj_count_3 = '0' ELSE
      yfi_1;

  
  tmp_11 <= tmp_8 WHEN varargout_2 = '0' ELSE
      tmp_10;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp10
  obj_FFTShiftTDObj_imPart <= to_signed(16#0000#, 16);

  
  tmp_12 <= tmp_11 WHEN obj_FFTShiftTDObj_resetSig = '0' ELSE
      obj_FFTShiftTDObj_imPart;

  obj_FFTShiftTDObj_imPart_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_FFTShiftTDObj_imPart_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_FFTShiftTDObj_imPart_1 <= tmp_12;
      END IF;
    END IF;
  END PROCESS obj_FFTShiftTDObj_imPart_reg_process;


  varargout_1_re_tmp <= obj_FFTShiftTDObj_rePart_1;
  varargout_1_im_tmp <= obj_FFTShiftTDObj_imPart_1;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp4
  obj_FFTShiftTDObj_validOut <= '0';

  
  tmp_13 <= varargout_2 WHEN obj_FFTShiftTDObj_resetSig = '0' ELSE
      obj_FFTShiftTDObj_validOut;

  obj_FFTShiftTDObj_validOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_FFTShiftTDObj_validOut_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_FFTShiftTDObj_validOut_1 <= tmp_13;
      END IF;
    END IF;
  END PROCESS obj_FFTShiftTDObj_validOut_reg_process;


  varargout_1_re_1 <= std_logic_vector(varargout_1_re_tmp);

  varargout_1_im_1 <= std_logic_vector(varargout_1_im_tmp);

  varargout_2_1 <= obj_FFTShiftTDObj_validOut_1;

END rtl;

