-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_axis_a_master.vhd
-- Created: 2025-11-19 10:43:26
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_axis_a_master
-- Source Path: Demodulat_ip/Demodulat_ip_axis_a_master
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Demodulat_ip_pkg.ALL;

ENTITY Demodulat_ip_axis_a_master IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        AXIS_A_Master_TREADY              :   IN    std_logic;  -- ufix1
        user_data                         :   IN    vector_of_std_logic_vector16(0 TO 1);  -- ufix16 [2]
        user_valid                        :   IN    std_logic;  -- ufix1
        packet_size_axis_a_master         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXIS_A_Master_TDATA               :   OUT   vector_of_std_logic_vector16(0 TO 1);  -- ufix16 [2]
        AXIS_A_Master_TVALID              :   OUT   std_logic;  -- ufix1
        AXIS_A_Master_TLAST               :   OUT   std_logic;  -- ufix1
        auto_ready                        :   OUT   std_logic  -- ufix1
        );
END Demodulat_ip_axis_a_master;


ARCHITECTURE rtl OF Demodulat_ip_axis_a_master IS

  -- Component Declarations
  COMPONENT Demodulat_ip_fifo_data_OUT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          Empty                           :   OUT   std_logic;  -- ufix1
          AFull                           :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT Demodulat_ip_fifo_data_OUT_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16
          );
  END COMPONENT;

  COMPONENT Demodulat_ip_fifo_TLAST_OUT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic;  -- ufix1
          Push                            :   IN    std_logic;  -- ufix1
          Pop                             :   IN    std_logic;  -- ufix1
          Out_rsvd                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Demodulat_ip_fifo_data_OUT
    USE ENTITY work.Demodulat_ip_fifo_data_OUT(rtl);

  FOR ALL : Demodulat_ip_fifo_data_OUT_block
    USE ENTITY work.Demodulat_ip_fifo_data_OUT_block(rtl);

  FOR ALL : Demodulat_ip_fifo_TLAST_OUT
    USE ENTITY work.Demodulat_ip_fifo_TLAST_OUT(rtl);

  -- Signals
  SIGNAL fifo_afull_data                  : std_logic;  -- ufix1
  SIGNAL internal_ready                   : std_logic;  -- ufix1
  SIGNAL internal_ready_delayed           : std_logic;  -- ufix1
  SIGNAL fifo_push                        : std_logic;  -- ufix1
  SIGNAL fifo_empty_data                  : std_logic;  -- ufix1
  SIGNAL AXIS_A_Master_TDATA_tmp          : vector_of_std_logic_vector16(0 TO 1);  -- ufix16 [2]
  SIGNAL packet_size_axis_a_master_unsigned : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_1                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL tlast_size_value                 : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL reg_packet_size_strobe           : std_logic;  -- ufix1
  SIGNAL auto_tlast                       : std_logic;  -- ufix1
  SIGNAL reset_TLAST                      : std_logic;  -- ufix1
  SIGNAL tlast_counter_out                : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL relop_relop1                     : std_logic;

BEGIN
  u_Demodulat_ip_fifo_data_OUT_inst : Demodulat_ip_fifo_data_OUT
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => user_data(0),  -- ufix16
              Push => fifo_push,  -- ufix1
              Pop => AXIS_A_Master_TREADY,  -- ufix1
              Out_rsvd => AXIS_A_Master_TDATA_tmp(0),  -- ufix16
              Empty => fifo_empty_data,  -- ufix1
              AFull => fifo_afull_data  -- ufix1
              );

  u_Demodulat_ip_fifo_data_OUT_inst_1 : Demodulat_ip_fifo_data_OUT_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => user_data(1),  -- ufix16
              Push => fifo_push,  -- ufix1
              Pop => AXIS_A_Master_TREADY,  -- ufix1
              Out_rsvd => AXIS_A_Master_TDATA_tmp(1)  -- ufix16
              );

  u_Demodulat_ip_fifo_TLAST_OUT_inst : Demodulat_ip_fifo_TLAST_OUT
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => auto_tlast,  -- ufix1
              Push => fifo_push,  -- ufix1
              Pop => AXIS_A_Master_TREADY,  -- ufix1
              Out_rsvd => AXIS_A_Master_TLAST  -- ufix1
              );

  internal_ready <=  NOT fifo_afull_data;

  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      internal_ready_delayed <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        internal_ready_delayed <= internal_ready;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  fifo_push <= internal_ready_delayed AND user_valid;


  AXIS_A_Master_TVALID <=  NOT fifo_empty_data;

  packet_size_axis_a_master_unsigned <= unsigned(packet_size_axis_a_master);

  const_1 <= to_unsigned(1, 32);

  tlast_size_value <= packet_size_axis_a_master_unsigned - const_1;

  reset_TLAST <= reg_packet_size_strobe OR auto_tlast;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  tlast_counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      tlast_counter_out <= to_unsigned(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF reset_TLAST = '1' THEN 
          tlast_counter_out <= to_unsigned(0, 32);
        ELSIF fifo_push = '1' THEN 
          tlast_counter_out <= tlast_counter_out + to_unsigned(1, 32);
        END IF;
      END IF;
    END IF;
  END PROCESS tlast_counter_process;


  
  relop_relop1 <= '1' WHEN tlast_counter_out = tlast_size_value ELSE
      '0';

  auto_tlast <= fifo_push AND relop_relop1;

  AXIS_A_Master_TDATA <= AXIS_A_Master_TDATA_tmp;

  auto_ready <= internal_ready;

END rtl;

