-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_src_OFDMDemod.vhd
-- Created: 2025-11-19 10:43:19
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_src_OFDMDemod
-- Source Path: genhdlOFDMDemodulatorChEstModel/Demodulation and Channel Estimation/OFDMDemod
-- Hierarchy Level: 1
-- Model version: 8.98
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Demodulat_ip_src_OFDMDemod IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1_re                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        In1_im                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        In2                               :   IN    std_logic;
        data_re                           :   OUT   std_logic_vector(43 DOWNTO 0);  -- sfix44_En30
        data_im                           :   OUT   std_logic_vector(43 DOWNTO 0);  -- sfix44_En30
        valid                             :   OUT   std_logic
        );
END Demodulat_ip_src_OFDMDemod;


ARCHITECTURE rtl OF Demodulat_ip_src_OFDMDemod IS

  -- Component Declarations
  COMPONENT Demodulat_ip_src_OFDM_Demodulator
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          data_re                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
          data_im                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
          valid                           :   IN    std_logic;
          data1_re                        :   OUT   std_logic_vector(43 DOWNTO 0);  -- sfix44_En30
          data1_im                        :   OUT   std_logic_vector(43 DOWNTO 0);  -- sfix44_En30
          valid1                          :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Demodulat_ip_src_OFDM_Demodulator
    USE ENTITY work.Demodulat_ip_src_OFDM_Demodulator(rtl);

  -- Signals
  SIGNAL data_re_tmp                      : std_logic_vector(43 DOWNTO 0);  -- ufix44
  SIGNAL data_im_tmp                      : std_logic_vector(43 DOWNTO 0);  -- ufix44

BEGIN
  u_OFDM_Demodulator : Demodulat_ip_src_OFDM_Demodulator
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              data_re => In1_re,  -- sfix32_En30
              data_im => In1_im,  -- sfix32_En30
              valid => In2,
              data1_re => data_re_tmp,  -- sfix44_En30
              data1_im => data_im_tmp,  -- sfix44_En30
              valid1 => valid
              );

  data_re <= data_re_tmp;

  data_im <= data_im_tmp;

END rtl;

