-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_src_CPRemoval_stage1.vhd
-- Created: 2025-12-04 17:31:13
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_src_CPRemoval_stage1
-- Source Path: 
-- Hierarchy Level: 3
-- Model version: 8.101
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Demodulat_ip_src_CPRemoval_stage1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        tmp_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        tmp_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        tmp                               :   IN    std_logic;
        tmp_1                             :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
        varargout_1_re                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        varargout_1_im                    :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        varargout_2                       :   OUT   std_logic
        );
END Demodulat_ip_src_CPRemoval_stage1;


ARCHITECTURE rtl OF Demodulat_ip_src_CPRemoval_stage1 IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL obj_CPRemoval_stage1Obj_validInReg : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_CPReg    : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_CPRemoval_stage1Obj_CPReg_1  : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_CPRemoval_stage1Obj_FFTReg   : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_CPRemoval_stage1Obj_FFTReg_1 : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_CPRemoval_stage1Obj_sampCnt  : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_2                            : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_CPRemoval_stage1Obj_idxposF  : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_CPRemoval_stage1Obj_CPLenSmpld : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_3                            : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL p111tmp_add_temp                 : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL obj_CPRemoval_stage1Obj_sampCnt_1 : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_4                            : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL p85tmp_sub_temp                  : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL tmp_5                            : std_logic;
  SIGNAL tmp_6                            : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL p79tmp_sub_cast                  : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL p79tmp_sub_cast_1                : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL p79tmp_sub_temp                  : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL p79tmp_cast                      : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL tmp_7                            : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_8                            : std_logic;
  SIGNAL tmp_9                            : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_10                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_11                           : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_FFTLenSampled : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_12                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_13                           : std_logic;
  SIGNAL tmp_14                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_15                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL p115tmp_add_temp                 : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL p113tmp_sub_cast                 : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL p113tmp_sub_cast_1               : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL p113tmp_sub_temp                 : signed(15 DOWNTO 0);  -- sfix16
  SIGNAL p113tmp_cast                     : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL tmp_16                           : std_logic;
  SIGNAL tmp_17                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_18                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_CPRemoval_stage1Obj_sampCntReg : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_19                           : std_logic;
  SIGNAL tmp_20                           : std_logic;
  SIGNAL tmp_unsigned                     : unsigned(15 DOWNTO 0);  -- ufix16_En15
  SIGNAL obj_CPRemoval_stage1Obj_CPFraction1 : unsigned(15 DOWNTO 0);  -- ufix16_En15
  SIGNAL tmp_21                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL p162tmp_mul_temp                 : unsigned(29 DOWNTO 0);  -- ufix30_En15
  SIGNAL obj_CPRemoval_stage1Obj_CPLenSampled : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_22                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_23                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL p109tmp_add_temp                 : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL tmp_24                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL p87tmp_sub_temp                  : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL obj_CPRemoval_stage1Obj_nextSymSamples : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_25                           : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_idxpos   : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_26                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_27                           : std_logic;
  SIGNAL tmp_28                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_29                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL obj_CPRemoval_stage1Obj_idxpos_1 : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_30                           : std_logic;
  SIGNAL tmp_31                           : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_ctrlSig  : std_logic;
  SIGNAL tmp_32                           : std_logic;
  SIGNAL tmp_33                           : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_ctrlSig_1 : std_logic;
  SIGNAL tmp_34                           : std_logic;
  SIGNAL tmp_35                           : std_logic;
  SIGNAL tmp_36                           : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_validInReg1 : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_validInReg2 : std_logic;
  SIGNAL tmp_37                           : std_logic;
  SIGNAL tmp_re_1                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_im_1                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_38                           : std_logic;
  SIGNAL tmp_re_signed                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_im_signed                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataReg_re : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataReg_im : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataInReg_re : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataInReg_im : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_re_2                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_im_2                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataInReg1_re : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataInReg1_im : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataInReg2_re : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataInReg2_im : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_re_3                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_im_3                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_re_4                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_im_4                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataOutReg_re : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataOutReg_im : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_re_5                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_im_5                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataOutReg1_re : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataOutReg1_im : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataOutReg2_re : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataOutReg2_im : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataOut_re : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL obj_CPRemoval_stage1Obj_dataOut_im : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL tmp_39                           : std_logic;
  SIGNAL tmp_40                           : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL p117tmp_add_temp                 : unsigned(14 DOWNTO 0);  -- ufix15
  SIGNAL obj_CPRemoval_stage1Obj_FFTPlusCPF : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL tmp_41                           : std_logic;
  SIGNAL out_rsvd                         : std_logic;
  SIGNAL out_rsvd_1                       : std_logic;
  SIGNAL out_rsvd_2                       : std_logic;
  SIGNAL tmp_42                           : std_logic;
  SIGNAL tmp_43                           : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_validOutReg : std_logic;
  SIGNAL tmp_44                           : std_logic;
  SIGNAL out_rsvd_3                       : std_logic;
  SIGNAL out_rsvd_4                       : std_logic;
  SIGNAL tmp_45                           : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_validOutReg1 : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_validOutReg2 : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_validOutReg3 : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_validOutReg4 : std_logic;
  SIGNAL obj_CPRemoval_stage1Obj_validOut : std_logic;

BEGIN
  obj_CPRemoval_stage1Obj_validInReg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validInReg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validInReg <= tmp;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validInReg_reg_process;


  obj_CPRemoval_stage1Obj_CPReg <= to_unsigned(16#0120#, 14);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp105
  obj_CPRemoval_stage1Obj_CPReg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_CPReg_1 <= to_unsigned(16#0010#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_CPReg_1 <= obj_CPRemoval_stage1Obj_CPReg;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_CPReg_reg_process;


  obj_CPRemoval_stage1Obj_FFTReg <= to_unsigned(16#1000#, 14);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp97
  obj_CPRemoval_stage1Obj_FFTReg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_FFTReg_1 <= to_unsigned(16#0040#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_FFTReg_1 <= obj_CPRemoval_stage1Obj_FFTReg;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_FFTReg_reg_process;


  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp75
  obj_CPRemoval_stage1Obj_sampCnt <= to_unsigned(16#0000#, 14);

  obj_CPRemoval_stage1Obj_idxposF_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_idxposF <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_idxposF <= tmp_2;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_idxposF_reg_process;


  p111tmp_add_temp <= resize(obj_CPRemoval_stage1Obj_CPLenSmpld, 15) + to_unsigned(16#0001#, 15);
  
  tmp_3 <= "11111111111111" WHEN p111tmp_add_temp(14) /= '0' ELSE
      p111tmp_add_temp(13 DOWNTO 0);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp81
  p85tmp_sub_temp <= resize(tmp_3, 15) - resize(obj_CPRemoval_stage1Obj_sampCnt_1, 15);
  
  tmp_4 <= "11111111111111" WHEN p85tmp_sub_temp(14) /= '0' ELSE
      p85tmp_sub_temp(13 DOWNTO 0);

  
  tmp_5 <= '1' WHEN tmp_4 < to_unsigned(16#0001#, 14) ELSE
      '0';

  
  tmp_2 <= obj_CPRemoval_stage1Obj_idxposF WHEN tmp_5 = '0' ELSE
      tmp_4;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp75
  p79tmp_sub_cast <= resize(tmp_2, 15);
  p79tmp_sub_cast_1 <= signed(resize(p79tmp_sub_cast, 16));
  p79tmp_sub_temp <= to_signed(16#0001#, 16) - p79tmp_sub_cast_1;
  
  p79tmp_cast <= "000000000000000" WHEN p79tmp_sub_temp(15) = '1' ELSE
      unsigned(p79tmp_sub_temp(14 DOWNTO 0));
  tmp_6 <= p79tmp_cast(13 DOWNTO 0);

  
  tmp_8 <= '1' WHEN obj_CPRemoval_stage1Obj_sampCnt_1 = tmp_7 ELSE
      '0';

  
  tmp_9 <= tmp_6 WHEN tmp_8 = '0' ELSE
      obj_CPRemoval_stage1Obj_sampCnt;

  tmp_10 <= obj_CPRemoval_stage1Obj_sampCnt_1 + to_unsigned(16#0001#, 14);

  tmp_11 <= hdlcoder_to_stdlogic(obj_CPRemoval_stage1Obj_sampCnt_1 < to_unsigned(16#0001#, 14)) AND obj_CPRemoval_stage1Obj_validInReg;

  
  tmp_12 <= obj_CPRemoval_stage1Obj_FFTLenSampled WHEN tmp_11 = '0' ELSE
      obj_CPRemoval_stage1Obj_FFTReg_1;

  obj_CPRemoval_stage1Obj_FFTLenSampled_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_FFTLenSampled <= to_unsigned(16#1000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_FFTLenSampled <= tmp_12;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_FFTLenSampled_reg_process;


  tmp_13 <= hdlcoder_to_stdlogic(obj_CPRemoval_stage1Obj_sampCnt_1 < to_unsigned(16#0001#, 14)) AND obj_CPRemoval_stage1Obj_validInReg;

  
  tmp_14 <= obj_CPRemoval_stage1Obj_CPLenSmpld WHEN tmp_13 = '0' ELSE
      obj_CPRemoval_stage1Obj_CPReg_1;

  obj_CPRemoval_stage1Obj_CPLenSmpld_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_CPLenSmpld <= to_unsigned(16#0010#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_CPLenSmpld <= tmp_14;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_CPLenSmpld_reg_process;


  p115tmp_add_temp <= resize(obj_CPRemoval_stage1Obj_CPLenSmpld, 15) + resize(obj_CPRemoval_stage1Obj_FFTLenSampled, 15);
  
  tmp_15 <= "11111111111111" WHEN p115tmp_add_temp(14) /= '0' ELSE
      p115tmp_add_temp(13 DOWNTO 0);

  p113tmp_sub_cast <= resize(tmp_15, 15);
  p113tmp_sub_cast_1 <= signed(resize(p113tmp_sub_cast, 16));
  p113tmp_sub_temp <= p113tmp_sub_cast_1 - to_signed(16#0001#, 16);
  
  p113tmp_cast <= "000000000000000" WHEN p113tmp_sub_temp(15) = '1' ELSE
      unsigned(p113tmp_sub_temp(14 DOWNTO 0));
  
  tmp_7 <= "11111111111111" WHEN p113tmp_cast(14) /= '0' ELSE
      p113tmp_cast(13 DOWNTO 0);

  
  tmp_16 <= '1' WHEN obj_CPRemoval_stage1Obj_sampCnt_1 >= tmp_7 ELSE
      '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp60
  
  tmp_17 <= tmp_10 WHEN tmp_16 = '0' ELSE
      tmp_9;

  
  tmp_18 <= obj_CPRemoval_stage1Obj_sampCnt_1 WHEN obj_CPRemoval_stage1Obj_validInReg = '0' ELSE
      tmp_17;

  obj_CPRemoval_stage1Obj_sampCnt_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_sampCnt_1 <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_sampCnt_1 <= tmp_18;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_sampCnt_reg_process;


  obj_CPRemoval_stage1Obj_sampCntReg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_sampCntReg <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_sampCntReg <= obj_CPRemoval_stage1Obj_sampCnt_1;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_sampCntReg_reg_process;


  
  tmp_19 <= '1' WHEN obj_CPRemoval_stage1Obj_sampCntReg = to_unsigned(16#0000#, 14) ELSE
      '0';

  tmp_20 <= hdlcoder_to_stdlogic(obj_CPRemoval_stage1Obj_sampCnt_1 < to_unsigned(16#0001#, 14)) AND obj_CPRemoval_stage1Obj_validInReg;

  tmp_unsigned <= unsigned(tmp_1);

  obj_CPRemoval_stage1Obj_CPFraction1_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_CPFraction1 <= to_unsigned(16#8000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_CPFraction1 <= tmp_unsigned;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_CPFraction1_reg_process;


  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp101
  p162tmp_mul_temp <= obj_CPRemoval_stage1Obj_CPReg_1 * obj_CPRemoval_stage1Obj_CPFraction1;
  
  tmp_21 <= "11111111111111" WHEN (p162tmp_mul_temp(29) /= '0') OR (p162tmp_mul_temp(28 DOWNTO 15) = "11111111111111") ELSE
      p162tmp_mul_temp(28 DOWNTO 15) + ('0' & p162tmp_mul_temp(14));

  
  tmp_22 <= obj_CPRemoval_stage1Obj_CPLenSampled WHEN tmp_20 = '0' ELSE
      tmp_21;

  obj_CPRemoval_stage1Obj_CPLenSampled_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_CPLenSampled <= to_unsigned(16#0001#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_CPLenSampled <= tmp_22;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_CPLenSampled_reg_process;


  p109tmp_add_temp <= resize(obj_CPRemoval_stage1Obj_CPLenSampled, 15) + to_unsigned(16#0001#, 15);
  
  tmp_23 <= "11111111111111" WHEN p109tmp_add_temp(14) /= '0' ELSE
      p109tmp_add_temp(13 DOWNTO 0);

  p87tmp_sub_temp <= resize(tmp_23, 15) - resize(obj_CPRemoval_stage1Obj_sampCnt_1, 15);
  
  tmp_24 <= "11111111111111" WHEN p87tmp_sub_temp(14) /= '0' ELSE
      p87tmp_sub_temp(13 DOWNTO 0);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp140
  obj_CPRemoval_stage1Obj_nextSymSamples_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_nextSymSamples <= to_unsigned(16#0001#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_nextSymSamples <= tmp_24;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_nextSymSamples_reg_process;


  
  tmp_25 <= '1' WHEN obj_CPRemoval_stage1Obj_nextSymSamples < to_unsigned(16#0001#, 14) ELSE
      '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp137
  obj_CPRemoval_stage1Obj_idxpos <= to_unsigned(16#0001#, 14);

  
  tmp_27 <= '1' WHEN tmp_26 /= to_unsigned(16#0000#, 14) ELSE
      '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp134
  
  tmp_28 <= tmp_26 WHEN tmp_27 = '0' ELSE
      obj_CPRemoval_stage1Obj_idxpos;

  obj_CPRemoval_stage1Obj_idxpos_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_idxpos_1 <= to_unsigned(16#0000#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_idxpos_1 <= tmp_29;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_idxpos_reg_process;


  
  tmp_26 <= obj_CPRemoval_stage1Obj_idxpos_1 WHEN tmp_25 = '0' ELSE
      obj_CPRemoval_stage1Obj_nextSymSamples;

  
  tmp_29 <= tmp_26 WHEN tmp_19 = '0' ELSE
      tmp_28;

  
  tmp_30 <= '1' WHEN tmp_29 /= to_unsigned(16#0000#, 14) ELSE
      '0';

  
  tmp_31 <= '1' WHEN obj_CPRemoval_stage1Obj_sampCnt_1 >= tmp_7 ELSE
      '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp63
  obj_CPRemoval_stage1Obj_ctrlSig <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp56
  
  tmp_33 <= tmp_32 WHEN tmp_31 = '0' ELSE
      obj_CPRemoval_stage1Obj_ctrlSig;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp130
  tmp_34 <=  NOT obj_CPRemoval_stage1Obj_ctrlSig_1;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp68
  
  tmp_35 <= obj_CPRemoval_stage1Obj_ctrlSig_1 WHEN tmp_30 = '0' ELSE
      tmp_34;

  
  tmp_32 <= obj_CPRemoval_stage1Obj_ctrlSig_1 WHEN obj_CPRemoval_stage1Obj_validInReg = '0' ELSE
      tmp_35;

  
  tmp_36 <= tmp_32 WHEN obj_CPRemoval_stage1Obj_validInReg = '0' ELSE
      tmp_33;

  obj_CPRemoval_stage1Obj_ctrlSig_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_ctrlSig_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_ctrlSig_1 <= tmp_36;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_ctrlSig_reg_process;


  obj_CPRemoval_stage1Obj_validInReg1_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validInReg1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validInReg1 <= obj_CPRemoval_stage1Obj_validInReg;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validInReg1_reg_process;


  obj_CPRemoval_stage1Obj_validInReg2_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validInReg2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validInReg2 <= obj_CPRemoval_stage1Obj_validInReg1;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validInReg2_reg_process;


  tmp_37 <= ( NOT obj_CPRemoval_stage1Obj_ctrlSig_1) OR obj_CPRemoval_stage1Obj_validInReg2;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl
  tmp_re_1 <= to_signed(16#0000#, 16);
  tmp_im_1 <= to_signed(16#0000#, 16);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp154
  
  tmp_38 <= '1' WHEN obj_CPRemoval_stage1Obj_idxpos_1 < to_unsigned(16#0001#, 14) ELSE
      '0';

  tmp_re_signed <= signed(tmp_re);

  tmp_im_signed <= signed(tmp_im);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp72
  obj_CPRemoval_stage1Obj_dataReg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_dataReg_re <= to_signed(16#0000#, 16);
      obj_CPRemoval_stage1Obj_dataReg_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_dataReg_re <= tmp_re_signed;
        obj_CPRemoval_stage1Obj_dataReg_im <= tmp_im_signed;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_dataReg_reg_process;


  
  tmp_re_2 <= obj_CPRemoval_stage1Obj_dataInReg_re WHEN obj_CPRemoval_stage1Obj_validInReg = '0' ELSE
      obj_CPRemoval_stage1Obj_dataReg_re;
  
  tmp_im_2 <= obj_CPRemoval_stage1Obj_dataInReg_im WHEN obj_CPRemoval_stage1Obj_validInReg = '0' ELSE
      obj_CPRemoval_stage1Obj_dataReg_im;

  obj_CPRemoval_stage1Obj_dataInReg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_dataInReg_re <= to_signed(16#0000#, 16);
      obj_CPRemoval_stage1Obj_dataInReg_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_dataInReg_re <= tmp_re_2;
        obj_CPRemoval_stage1Obj_dataInReg_im <= tmp_im_2;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_dataInReg_reg_process;


  obj_CPRemoval_stage1Obj_dataInReg1_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_dataInReg1_re <= to_signed(16#0000#, 16);
      obj_CPRemoval_stage1Obj_dataInReg1_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_dataInReg1_re <= obj_CPRemoval_stage1Obj_dataInReg_re;
        obj_CPRemoval_stage1Obj_dataInReg1_im <= obj_CPRemoval_stage1Obj_dataInReg_im;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_dataInReg1_reg_process;


  obj_CPRemoval_stage1Obj_dataInReg2_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_dataInReg2_re <= to_signed(16#0000#, 16);
      obj_CPRemoval_stage1Obj_dataInReg2_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_dataInReg2_re <= obj_CPRemoval_stage1Obj_dataInReg1_re;
        obj_CPRemoval_stage1Obj_dataInReg2_im <= obj_CPRemoval_stage1Obj_dataInReg1_im;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_dataInReg2_reg_process;


  
  tmp_re_3 <= obj_CPRemoval_stage1Obj_dataInReg1_re WHEN tmp_38 = '0' ELSE
      obj_CPRemoval_stage1Obj_dataInReg2_re;
  
  tmp_im_3 <= obj_CPRemoval_stage1Obj_dataInReg1_im WHEN tmp_38 = '0' ELSE
      obj_CPRemoval_stage1Obj_dataInReg2_im;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp144
  
  tmp_re_4 <= tmp_re_1 WHEN tmp_37 = '0' ELSE
      tmp_re_3;
  
  tmp_im_4 <= tmp_im_1 WHEN tmp_37 = '0' ELSE
      tmp_im_3;

  
  tmp_re_5 <= obj_CPRemoval_stage1Obj_dataOutReg_re WHEN tmp_37 = '0' ELSE
      tmp_re_4;
  
  tmp_im_5 <= obj_CPRemoval_stage1Obj_dataOutReg_im WHEN tmp_37 = '0' ELSE
      tmp_im_4;

  obj_CPRemoval_stage1Obj_dataOutReg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_dataOutReg_re <= to_signed(16#0000#, 16);
      obj_CPRemoval_stage1Obj_dataOutReg_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_dataOutReg_re <= tmp_re_5;
        obj_CPRemoval_stage1Obj_dataOutReg_im <= tmp_im_5;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_dataOutReg_reg_process;


  obj_CPRemoval_stage1Obj_dataOutReg1_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_dataOutReg1_re <= to_signed(16#0000#, 16);
      obj_CPRemoval_stage1Obj_dataOutReg1_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_dataOutReg1_re <= obj_CPRemoval_stage1Obj_dataOutReg_re;
        obj_CPRemoval_stage1Obj_dataOutReg1_im <= obj_CPRemoval_stage1Obj_dataOutReg_im;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_dataOutReg1_reg_process;


  obj_CPRemoval_stage1Obj_dataOutReg2_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_dataOutReg2_re <= to_signed(16#0000#, 16);
      obj_CPRemoval_stage1Obj_dataOutReg2_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_dataOutReg2_re <= obj_CPRemoval_stage1Obj_dataOutReg1_re;
        obj_CPRemoval_stage1Obj_dataOutReg2_im <= obj_CPRemoval_stage1Obj_dataOutReg1_im;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_dataOutReg2_reg_process;


  obj_CPRemoval_stage1Obj_dataOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_dataOut_re <= to_signed(16#0000#, 16);
      obj_CPRemoval_stage1Obj_dataOut_im <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_dataOut_re <= obj_CPRemoval_stage1Obj_dataOutReg2_re;
        obj_CPRemoval_stage1Obj_dataOut_im <= obj_CPRemoval_stage1Obj_dataOutReg2_im;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_dataOut_reg_process;


  varargout_1_re <= std_logic_vector(obj_CPRemoval_stage1Obj_dataOut_re);

  varargout_1_im <= std_logic_vector(obj_CPRemoval_stage1Obj_dataOut_im);

  
  tmp_39 <= '1' WHEN obj_CPRemoval_stage1Obj_sampCntReg >= obj_CPRemoval_stage1Obj_CPLenSampled ELSE
      '0';

  p117tmp_add_temp <= resize(obj_CPRemoval_stage1Obj_CPLenSampled, 15) + resize(obj_CPRemoval_stage1Obj_FFTLenSampled, 15);
  
  tmp_40 <= "11111111111111" WHEN p117tmp_add_temp(14) /= '0' ELSE
      p117tmp_add_temp(13 DOWNTO 0);

  obj_CPRemoval_stage1Obj_FFTPlusCPF_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_FFTPlusCPF <= to_unsigned(16#0040#, 14);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_FFTPlusCPF <= tmp_40;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_FFTPlusCPF_reg_process;


  
  tmp_41 <= '1' WHEN obj_CPRemoval_stage1Obj_sampCntReg < obj_CPRemoval_stage1Obj_FFTPlusCPF ELSE
      '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp158
  out_rsvd <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp121
  out_rsvd_1 <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp158
  out_rsvd_2 <= '1';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp121
  
  tmp_42 <= out_rsvd WHEN tmp_41 = '0' ELSE
      out_rsvd_2;

  
  tmp_43 <= out_rsvd_1 WHEN tmp_39 = '0' ELSE
      tmp_42;

  obj_CPRemoval_stage1Obj_validOutReg_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validOutReg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validOutReg <= tmp_43;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validOutReg_reg_process;


  tmp_44 <= obj_CPRemoval_stage1Obj_validOutReg AND obj_CPRemoval_stage1Obj_validInReg2;

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp126
  out_rsvd_3 <= '0';

  -- HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp126
  out_rsvd_4 <= '1';

  
  tmp_45 <= out_rsvd_3 WHEN tmp_44 = '0' ELSE
      out_rsvd_4;

  obj_CPRemoval_stage1Obj_validOutReg1_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validOutReg1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validOutReg1 <= tmp_45;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validOutReg1_reg_process;


  obj_CPRemoval_stage1Obj_validOutReg2_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validOutReg2 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validOutReg2 <= obj_CPRemoval_stage1Obj_validOutReg1;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validOutReg2_reg_process;


  obj_CPRemoval_stage1Obj_validOutReg3_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validOutReg3 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validOutReg3 <= obj_CPRemoval_stage1Obj_validOutReg2;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validOutReg3_reg_process;


  obj_CPRemoval_stage1Obj_validOutReg4_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validOutReg4 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validOutReg4 <= obj_CPRemoval_stage1Obj_validOutReg3;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validOutReg4_reg_process;


  obj_CPRemoval_stage1Obj_validOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_CPRemoval_stage1Obj_validOut <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_CPRemoval_stage1Obj_validOut <= obj_CPRemoval_stage1Obj_validOutReg4;
      END IF;
    END IF;
  END PROCESS obj_CPRemoval_stage1Obj_validOut_reg_process;


  varargout_2 <= obj_CPRemoval_stage1Obj_validOut;

END rtl;

