-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_dut.vhd
-- Created: 2025-11-19 10:43:26
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_dut
-- Source Path: Demodulat_ip/Demodulat_ip_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Demodulat_ip_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        In1_re                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        In1_im                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        In2                               :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        dataOut_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dataOut_im                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validOut                          :   OUT   std_logic  -- ufix1
        );
END Demodulat_ip_dut;


ARCHITECTURE rtl OF Demodulat_ip_dut IS

  -- Component Declarations
  COMPONENT Demodulat_ip_src_Demodulation_and_Channel_Estimation
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          In1_re                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
          In1_im                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
          In2                             :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          dataOut_re                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dataOut_im                      :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Demodulat_ip_src_Demodulation_and_Channel_Estimation
    USE ENTITY work.Demodulat_ip_src_Demodulation_and_Channel_Estimation(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL In2_sig                          : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL dataOut_re_sig                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dataOut_im_sig                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL validOut_sig                     : std_logic;  -- ufix1

BEGIN
  u_Demodulat_ip_src_Demodulation_and_Channel_Estimation : Demodulat_ip_src_Demodulation_and_Channel_Estimation
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              In1_re => In1_re,  -- sfix32_En30
              In1_im => In1_im,  -- sfix32_En30
              In2 => In2_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              dataOut_re => dataOut_re_sig,  -- sfix16_En14
              dataOut_im => dataOut_im_sig,  -- sfix16_En14
              validOut => validOut_sig  -- ufix1
              );

  In2_sig <= In2;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  dataOut_re <= dataOut_re_sig;

  dataOut_im <= dataOut_im_sig;

  validOut <= validOut_sig;

END rtl;

