-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/genhdlOFDMDemodulatorChEstModel/Demodulat_ip_src_OFDM_Demodulator.vhd
-- Created: 2025-12-04 17:31:13
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Demodulat_ip_src_OFDM_Demodulator
-- Source Path: genhdlOFDMDemodulatorChEstModel/Demodulation and Channel Estimation/OFDMDemod/OFDM Demodulator
-- Hierarchy Level: 2
-- Model version: 8.101
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Demodulat_ip_src_OFDM_Demodulator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        data_re                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        data_im                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        valid                             :   IN    std_logic;
        data1_re                          :   OUT   std_logic_vector(27 DOWNTO 0);  -- sfix28_En14
        data1_im                          :   OUT   std_logic_vector(27 DOWNTO 0);  -- sfix28_En14
        valid1                            :   OUT   std_logic
        );
END Demodulat_ip_src_OFDM_Demodulator;


ARCHITECTURE rtl OF Demodulat_ip_src_OFDM_Demodulator IS

  -- Component Declarations
  COMPONENT Demodulat_ip_src_CPRemoval_stage1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          tmp_re                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tmp_im                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          tmp                             :   IN    std_logic;
          tmp_1                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En15
          varargout_1_re                  :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          varargout_1_im                  :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          varargout_2                     :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Demodulat_ip_src_HDLFFTShift
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          varargout_1_re                  :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          varargout_1_im                  :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          varargout_2                     :   IN    std_logic;
          varargout_1_re_1                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          varargout_1_im_1                :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          varargout_2_1                   :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Demodulat_ip_src_dsphdl_FFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(27 DOWNTO 0);  -- sfix28_En14
          dataOut_im                      :   OUT   std_logic_vector(27 DOWNTO 0);  -- sfix28_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Demodulat_ip_src_SubcarrierSelector
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          varargout_1_re                  :   IN    std_logic_vector(27 DOWNTO 0);  -- sfix28_En14
          varargout_1_im                  :   IN    std_logic_vector(27 DOWNTO 0);  -- sfix28_En14
          varargout_2                     :   IN    std_logic;
          varargout_1_re_1                :   OUT   std_logic_vector(27 DOWNTO 0);  -- sfix28_En14
          varargout_1_im_1                :   OUT   std_logic_vector(27 DOWNTO 0);  -- sfix28_En14
          varargout_2_1                   :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Demodulat_ip_src_CPRemoval_stage1
    USE ENTITY work.Demodulat_ip_src_CPRemoval_stage1(rtl);

  FOR ALL : Demodulat_ip_src_HDLFFTShift
    USE ENTITY work.Demodulat_ip_src_HDLFFTShift(rtl);

  FOR ALL : Demodulat_ip_src_dsphdl_FFT
    USE ENTITY work.Demodulat_ip_src_dsphdl_FFT(rtl);

  FOR ALL : Demodulat_ip_src_SubcarrierSelector
    USE ENTITY work.Demodulat_ip_src_SubcarrierSelector(rtl);

  -- Signals
  SIGNAL obj_cpFracValue                  : unsigned(15 DOWNTO 0);  -- ufix16_En15
  SIGNAL varargout_1_re                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL varargout_1_im                   : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL varargout_2                      : std_logic;
  SIGNAL varargout_1_re_1                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL varargout_1_im_1                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL varargout_2_1                    : std_logic;
  SIGNAL varargout_1_re_2                 : std_logic_vector(27 DOWNTO 0);  -- ufix28
  SIGNAL varargout_1_im_2                 : std_logic_vector(27 DOWNTO 0);  -- ufix28
  SIGNAL varargout_2_2                    : std_logic;
  SIGNAL varargout_1_re_3                 : std_logic_vector(27 DOWNTO 0);  -- ufix28
  SIGNAL varargout_1_im_3                 : std_logic_vector(27 DOWNTO 0);  -- ufix28
  SIGNAL varargout_2_3                    : std_logic;
  SIGNAL varargout_1_re_signed            : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL varargout_1_im_signed            : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL obj_dataOut_re                   : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL obj_dataOut_im                   : signed(27 DOWNTO 0);  -- sfix28_En14
  SIGNAL valid_1                          : std_logic;

BEGIN
  u_CPRemoval_stage1 : Demodulat_ip_src_CPRemoval_stage1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              tmp_re => data_re,  -- sfix16_En14
              tmp_im => data_im,  -- sfix16_En14
              tmp => valid,
              tmp_1 => std_logic_vector(obj_cpFracValue),  -- ufix16_En15
              varargout_1_re => varargout_1_re,  -- sfix16_En14
              varargout_1_im => varargout_1_im,  -- sfix16_En14
              varargout_2 => varargout_2
              );

  u_HDLFFTShift : Demodulat_ip_src_HDLFFTShift
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              varargout_1_re => varargout_1_re,  -- sfix16_En14
              varargout_1_im => varargout_1_im,  -- sfix16_En14
              varargout_2 => varargout_2,
              varargout_1_re_1 => varargout_1_re_1,  -- sfix16_En14
              varargout_1_im_1 => varargout_1_im_1,  -- sfix16_En14
              varargout_2_1 => varargout_2_1
              );

  u_dsphdl_FFT : Demodulat_ip_src_dsphdl_FFT
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn_re => varargout_1_re_1,  -- sfix16_En14
              dataIn_im => varargout_1_im_1,  -- sfix16_En14
              validIn => varargout_2_1,
              dataOut_re => varargout_1_re_2,  -- sfix28_En14
              dataOut_im => varargout_1_im_2,  -- sfix28_En14
              validOut => varargout_2_2
              );

  u_SubcarrierSelector : Demodulat_ip_src_SubcarrierSelector
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              varargout_1_re => varargout_1_re_2,  -- sfix28_En14
              varargout_1_im => varargout_1_im_2,  -- sfix28_En14
              varargout_2 => varargout_2_2,
              varargout_1_re_1 => varargout_1_re_3,  -- sfix28_En14
              varargout_1_im_1 => varargout_1_im_3,  -- sfix28_En14
              varargout_2_1 => varargout_2_3
              );

  obj_cpFracValue <= to_unsigned(16#8000#, 16);

  varargout_1_re_signed <= signed(varargout_1_re_3);

  varargout_1_im_signed <= signed(varargout_1_im_3);

  -- HDL code generation from MATLAB function: SystemCore_stepImpl
  obj_dataOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      obj_dataOut_re <= to_signed(16#0000000#, 28);
      obj_dataOut_im <= to_signed(16#0000000#, 28);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        obj_dataOut_re <= varargout_1_re_signed;
        obj_dataOut_im <= varargout_1_im_signed;
      END IF;
    END IF;
  END PROCESS obj_dataOut_reg_process;


  data1_re <= std_logic_vector(obj_dataOut_re);

  data1_im <= std_logic_vector(obj_dataOut_im);

  obj_validOut_reg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      valid_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        valid_1 <= varargout_2_3;
      END IF;
    END IF;
  END PROCESS obj_validOut_reg_process;


  valid1 <= valid_1;

END rtl;

